# Generated by Django 5.2.4 on 2025-07-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('service_type', models.CharField(choices=[('business', 'Start Business'), ('ngo', 'NGO'), ('compliance', 'Compliance'), ('advisory', 'Advisory')], default='business', max_length=20)),
            ],
        ),
    ]
