# Generated by Django 5.2.4 on 2025-07-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='header',
            field=models.CharField(default='General', max_length=200),
        ),
    ]
