# Generated by Django 5.2.4 on 2025-07-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_service_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('business', 'Start Business'), ('ngo', 'NGO'), ('compliance', 'Compliance'), ('trademark', 'Trademark')], default='business', max_length=20),
        ),
    ]
